services:
  db:
    image: postgres:18.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - layered-frontend-demo_postgres_data:/var/lib/postgresql/18/docker
  redis:
    image: redis:8.2.2
    ports:
      - '6379:6379'
    volumes:
      - layered-frontend-demo_redis_data:/data
volumes:
  layered-frontend-demo_postgres_data:
  layered-frontend-demo_redis_data:
